### ISSUE TITLE
pay me dued

### ISSUE THREAD

**Issue by DavidTechnoboy** [Electromaster232/Electro-Cogs#7]
yeah i saw [this file](https://github.com/Electromaster232/Electro-Cogs/blob/master/peopleelectroneedtopay.md) in your repo and i need to be on it BECAUSE I CAN ONLY SET 3 HOMES AND I PAID TO SET 4!!!!! k thx bye refund ;)

**Comment by Electromaster232** [comment]
dued. Try joining I think I fixed it

**Comment by DavidTechnoboy** [comment]
uhh you didnt fix

**Comment by Electromaster232** [comment]
https://github.com/drtshock/Essentials/issues/1568

**Comment by DavidTechnoboy** [comment]
im on the list now :D

**Comment by DavidTechnoboy** [comment]
[that proves nothing](https://i.imgur.com/AxXwe6r.png)

**Comment by Electromaster232** [comment]
@DavidTechnoboy got a reply - so I should get an answer soon.

**Comment by DavidTechnoboy** [comment]
wtf

**Comment by DavidTechnoboy** [comment]
**WORKS NOW AYYY LMAO XDXDXDXDXD**
